### ISSUE TITLE
Add advice for asking for letters of recommendation

### ISSUE THREAD

**Issue by sbryngelson** [poloclub/awesome-grad-school#2]
Add advice for how to best request letters of recommendation from supervisors (or otherwise), and what to provide those letter writers should they accept.

**Comment by xiaohk** [comment]
This [twitter thread](https://twitter.com/jbhuang0604/status/1522072974068703233?s=61&t=JSKBPkLnzxG6YdQdoiCpoA) comes to my mind.

**Comment by sbryngelson** [comment]
Closed with c64575b337c21c4c734ea375e260e7745318fa8e
